/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriverOnboardingRouteImport } from './routes/driver-onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminInfoRouteImport } from './routes/admin-info'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedDriverPaymentRouteImport } from './routes/_authenticated/driver-payment'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const DriverOnboardingRoute = DriverOnboardingRouteImport.update({
  id: '/driver-onboarding',
  path: '/driver-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInfoRoute = AdminInfoRouteImport.update({
  id: '/admin-info',
  path: '/admin-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverPaymentRoute =
  AuthenticatedDriverPaymentRouteImport.update({
    id: '/driver-payment',
    path: '/driver-payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-info': typeof AdminInfoRoute
  '/auth': typeof AuthRoute
  '/driver-onboarding': typeof DriverOnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/driver-payment': typeof AuthenticatedDriverPaymentRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/history': typeof AuthenticatedHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-info': typeof AdminInfoRoute
  '/auth': typeof AuthRoute
  '/driver-onboarding': typeof DriverOnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/driver-payment': typeof AuthenticatedDriverPaymentRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/history': typeof AuthenticatedHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-info': typeof AdminInfoRoute
  '/auth': typeof AuthRoute
  '/driver-onboarding': typeof DriverOnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/driver-payment': typeof AuthenticatedDriverPaymentRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-info'
    | '/auth'
    | '/driver-onboarding'
    | '/admin'
    | '/app'
    | '/driver-payment'
    | '/earnings'
    | '/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-info'
    | '/auth'
    | '/driver-onboarding'
    | '/admin'
    | '/app'
    | '/driver-payment'
    | '/earnings'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-info'
    | '/auth'
    | '/driver-onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/driver-payment'
    | '/_authenticated/earnings'
    | '/_authenticated/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminInfoRoute: typeof AdminInfoRoute
  AuthRoute: typeof AuthRoute
  DriverOnboardingRoute: typeof DriverOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/driver-onboarding': {
      id: '/driver-onboarding'
      path: '/driver-onboarding'
      fullPath: '/driver-onboarding'
      preLoaderRoute: typeof DriverOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-info': {
      id: '/admin-info'
      path: '/admin-info'
      fullPath: '/admin-info'
      preLoaderRoute: typeof AdminInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver-payment': {
      id: '/_authenticated/driver-payment'
      path: '/driver-payment'
      fullPath: '/driver-payment'
      preLoaderRoute: typeof AuthenticatedDriverPaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDriverPaymentRoute: typeof AuthenticatedDriverPaymentRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDriverPaymentRoute: AuthenticatedDriverPaymentRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminInfoRoute: AdminInfoRoute,
  AuthRoute: AuthRoute,
  DriverOnboardingRoute: DriverOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
